apiVersion: v1
kind: Service
metadata:
  name: {{ template "tomcat.fullname" . }}
  labels:
    app: {{ template "tomcat.fullname" . }}
    tier: {{ .Values.service.frontend.selector.tier }}
    chart: {{ template "tomcat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{.Values.service.frontend.port}}
  selector:
    app: {{.Values.service.frontend.selector.app}}
    tier: {{.Values.service.frontend.selector.tier}}
