name: tomcat
description: Deploy a basic tomcat application server
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
version: 0.1.0
appVersion: 7.0
home: https://github.com/yahavb
sources:
  - https://github.com/yahavb
maintainers:
  - name: Yahav Biran
    email: ybiran@ananware.systems
  - name: Joel Dubow
    email: jdubow@ananware.systems
