# Default values for the chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  webarchive:
    repository: ananwaresystems/webarchive
    tag: "1.0"
  tomcat:
    repository: ananwaresystems/tomcat
    tag: "7.0"
  pullPolicy: IfNotPresent
deploy:
  directory: /root/apache-tomcat-7.0.42-v2/webapps
service:
  name: http
  type: LoadBalancer
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi
nodeSelector: {}
tolerations: []
cmd:
  start: "/root/apache-tomcat-7.0.42-v2/bin/start.sh"
